name: eweso-web-devtools
services:
  php:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - .:/opt/project
      - .docker/auth.json:/root/.config/composer/auth.json
    command: tail -f /dev/null
